"""Neuron, synapse and plasticity models, and the runner that scans them over time.

Every neuron model meets one contract (`sparx.dynamics.core`):
`init_state(shape, dtype)` and `step(state, SynapticInput, dt) -> (state,
Output)`, and `run(model, inputs)` scans one over time. A model's output is
its spikes, or a graded value each step when the model is `graded`. Two families meet
it. `sparx.dynamics.ml` holds the dimensionless, one-step-is-one-unit
models deep spiking networks train with: soft resets, detached resets,
learnable decays, input as a jump of the membrane. `sparx.dynamics.neurons`
holds models of neurons as biology measures them: membrane equations in mV
and ms with conductances, refractoriness and reversal potentials. Synapses
with receptor kinetics and plasticity rules complete them; `sparx.nn` builds
layers from these models and `sparx.graph` builds circuits and connectomes
(design.md sections 4 and 5).

This package exports the models and the contract. The arithmetic the
models share (`fire`, `exact_linear`, `rk4`, `substeps` and the rest), which
a new model is written with, stays in `sparx.dynamics.core`.
"""

from sparx.dynamics.core import Gap, Model, NeuronModel, Output, Reset, SynapticInput, Term, decay, run
from sparx.dynamics.homeostasis import IntrinsicPlasticity, IntrinsicState
from sparx.dynamics.ml import (
    ACTIVATIONS,
    ALIFCell,
    ALIFState,
    BernoulliCell,
    BernoulliState,
    DecayingHebb,
    Dense,
    EligibleHebb,
    FastWeights,
    HebbianRule,
    LICell,
    LIFCell,
    MembraneState,
    ModulatedHebb,
    OjaHebb,
    PulseCell,
    RateCell,
    RateState,
    RecurrentCell,
    RecurrentState,
    RetroactiveHebb,
    Serial,
    Sparse,
    Wiring,
)
from sparx.dynamics.neurons import (
    IZHIKEVICH_2003,
    IZHIKEVICH_2004,
    RECEPTORS,
    AdEx,
    AdExState,
    GradedPotential,
    GradedPotentialState,
    HodgkinHuxley,
    HodgkinHuxleyState,
    Izhikevich,
    IzhikevichState,
    LeakyIntegrateAndFire,
    LeakyIntegrateAndFireState,
    MgBlock,
    izhikevich_2003,
    izhikevich_2004,
)
from sparx.dynamics.plasticity import (
    DopamineSTDP,
    DopamineTraces,
    PairSTDP,
    Plasticity,
    Rules,
    ScalingTraces,
    STDPTraces,
    SynapticScaling,
    TripletSTDP,
    TripletTraces,
    TsodyksMarkram,
    TsodyksMarkramState,
)
from sparx.dynamics.synapses import (
    Alpha,
    AlphaState,
    Arrivals,
    BiExponential,
    BiExponentialState,
    Delta,
    Exponential,
    Graded,
    GradedState,
    Landing,
    PointNeuron,
    PointNeuronState,
    Receptor,
    StochasticRelease,
    SynapseModel,
)

__all__ = [
    "ACTIVATIONS",
    "IZHIKEVICH_2003",
    "IZHIKEVICH_2004",
    "RECEPTORS",
    "ALIFCell",
    "ALIFState",
    "AdEx",
    "AdExState",
    "Alpha",
    "AlphaState",
    "Arrivals",
    "BernoulliCell",
    "BernoulliState",
    "BiExponential",
    "BiExponentialState",
    "DecayingHebb",
    "Delta",
    "Dense",
    "DopamineSTDP",
    "DopamineTraces",
    "EligibleHebb",
    "Exponential",
    "FastWeights",
    "Gap",
    "Graded",
    "GradedPotential",
    "GradedPotentialState",
    "GradedState",
    "HebbianRule",
    "HodgkinHuxley",
    "HodgkinHuxleyState",
    "IntrinsicPlasticity",
    "IntrinsicState",
    "Izhikevich",
    "IzhikevichState",
    "LICell",
    "LIFCell",
    "Landing",
    "LeakyIntegrateAndFire",
    "LeakyIntegrateAndFireState",
    "MembraneState",
    "MgBlock",
    "Model",
    "ModulatedHebb",
    "NeuronModel",
    "OjaHebb",
    "Output",
    "PairSTDP",
    "Plasticity",
    "PointNeuron",
    "PointNeuronState",
    "PulseCell",
    "RateCell",
    "RateState",
    "Receptor",
    "RecurrentCell",
    "RecurrentState",
    "Reset",
    "RetroactiveHebb",
    "Rules",
    "STDPTraces",
    "ScalingTraces",
    "Serial",
    "Sparse",
    "StochasticRelease",
    "SynapseModel",
    "SynapticInput",
    "SynapticScaling",
    "Term",
    "TripletSTDP",
    "TripletTraces",
    "TsodyksMarkram",
    "TsodyksMarkramState",
    "Wiring",
    "decay",
    "izhikevich_2003",
    "izhikevich_2004",
    "run",
]
